---
- include: packages.yml

  # Read Jitsi Meet config files and extract secrets for use in template configs.
  # Import to run these tasks after package installation, but before config tasks.
- include: dynamic_vars.yml

- include: prosody.yml

- include: jitsi_meet.yml

- include: jicofo.yml

- include: nginx.yml

- include: ufw.yml
