---
- name: Copy Prosody config template.
  template:
    src: prosody_config.j2
    dest: "/etc/prosody/conf.avail/{{ jitsi_meet_server_name }}.cfg.lua"
    owner: root
    group: root
    mode: "0644"
    # Simply syntax check for validation, doesn't catch config errors.
    validate: "luac -p %s"
  notify: restart prosody

- name: Symlink Prosody config by domain name.
  file:
    path: "/etc/prosody/conf.d/{{ jitsi_meet_server_name }}.cfg.lua"
    state: link
    src: "/etc/prosody/conf.avail/{{ jitsi_meet_server_name }}.cfg.lua"
  notify: restart prosody

- name: Create Prosody config dir for Jicofo auth info.
  file:
    path: /var/lib/prosody/{{ 'auth%2e'+jitsi_meet_server_name | replace('.', '%2e') }}/accounts/
    state: directory
    owner: prosody
    group: prosody
    mode: "0750"

- name: Register Jicofo user with Prosody service.
  template:
    src: prosody_focus_auth.j2
    # Yes, prosody actually URL-escapes the directory name for some reason.
    dest: /var/lib/prosody/{{ 'auth%2e'+jitsi_meet_server_name | replace('.', '%2e') }}/accounts/focus.dat
  notify:
    - restart jicofo
    - restart prosody
